name: Condense Files & Upload

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
  workflow_dispatch:
    
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update trips.txt
      run: node index.js file=trips.txt
    - name: Logining in to Git
      run: |
        git config --global user.email "${{ secrets.EMAIL }}"
        git config --global user.name "${{ github.actor }} (via GitHub Actions)"
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "Auto updating trips.txt"
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master
    
      
