name: Condense Files & Upload

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
  workflow_dispatch:
    
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update trips.txt
      run: node index.js file=trips.txt
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: gtfs/
    
      
