name: Condense Files & Upload

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
  workflow_dispatch:
    
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update trips.txt
      run: node index.js file=trips.txt
    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
          file-path: |
              gtfs/trips.txt
              gtfs/stop_times.txt
          commit-msg: Update resources (Via GitHub Actions)
          github-token: ${{ secrets.GH_TOKEN }}
          
      
