# (c) 2023 Benjamin-Del


name: Update GTFS database
run-name: Update GTFS database

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
  workflow_dispatch:
  #push:
  # Remove Push as it is interfering with GH pages deployment
    
jobs:
  run-script:
    runs-on: ubuntu-latest
    name:  Update GTFS database
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update OC Transpo Data
      run: |
        node oct.js file=trips.txt
        node oct.js file=stop_times.txt
        node oct.js file=calendar.txt
        node oct.js file=routes.txt
        node oct.js file=shapes.txt
        node oct.js file=stops.txt
    - name: Update STO Data
      run: |
        node sto.js file=trips.txt
        node sto.js file=stop_times.txt
        node sto.js file=calendar_dates.txt
        node sto.js file=routes.txt
        node sto.js file=shapes.txt
        node sto.js file=stops.txt
    - name: Update VIA Data
      run: |
        node via.js file=trips.txt
        node via.js file=stop_times.txt
        node via.js file=calendar.txt
        node via.js file=routes.txt
        node via.js file=shapes.txt
        node via.js file=stops.txt
    - name: Finish Update
      run: node update.js
    - name: Push Update
      run: |
        git config --global user.name "${{ github.actor }} [Via GitHub Actions]"
        git config --global user.email "${{ secrets.EMAIL }}"
  
        git add -A
        git commit --allow-empty -m "Update files via GH Actions"
        git push