# (c) 2023 Benjamin-Del


name: Update GTFS database
run-name: Update GTFS database

on:
  schedule:
    - cron: '0 5 * * *'  # 1:00 AM EDT / 12:00 AM EST
  workflow_dispatch:
  #push:
  # Remove Push as it is interfering with GH pages deployment
    
jobs:
  build:
    runs-on: ubuntu-latest
    name:  Update GTFS database
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # Setup the pages
    - name: Update OC Transpo Data
      run: |
        npm install
        npx prisma generate
        node main.js
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
