name: Update Files

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight UTC
  workflow_dispatch:
    
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update Trip
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: node index.js token="${{ env.GH_TOKEN }}"
